name: $(date:yyyymmdd)$(rev:.rr) #20191209.00

trigger:
  - master

stages:
  - stage: compile
    jobs:
      - job: aspnet
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: |
              dotnet build 3_devops/Devops.sln
  - stage: test
    jobs:
      - job: aspnet_test
        pool:
            vnImage: ubuntu-18.04
        steps:
          - tasks: DotNetCoreCLI@2
            inputs:
              command: test
              project: 3_devops/Devops.sln
              arguments: --collect:"XPlat Code Coverage"
          - task: PublishCodeCoverageResult@1
              inputs:
                codeCoverageTool: cobertura
                summaryFileLocation: '**/TestResults/coverage.cobertura.xml'
  # - stage: analyze
  #   jobs:
  #     - job:
  #       pool:
  #         vmImage: ubuntu-18.04
  #       steps:
  #           - script: dotnet install --global dotnet-sonarscanner
  #           - script: |
  #             sonarscanner begin /k:devops-henry /d:sonar-login=$(SONAR_LOGIN)
  #             dotnet build
  #             dotnet test
  #             sonarscanner end /d:sonar-login=$(SONAR_LOGIN)
  # - stage: pack
  #   jobs:
  #     - job:
  #       pool:
  #        vmImage: ubuntu-18.04
  #       steps:
  #         - script: docker image build -f 3_devops/dockerfile -t hlhuynh14/devops:$(BUILD_NAME)
  #         - script: docker login -username $(DOCKER_USER) --password $(DOCKER_TOKEN)
  #         - script: docker image push hlhuynh14/devops:$(BUILD_NAME)

